commands/chincome.js

Proof that it works!
https://cdn.discordapp.com/attachments/598768025289883649/737494832599269457/unknown.png
It's pretty self-documenting which will make it easy to use.

Chincome Calculator

---

commands/2tc.js

**Changes**:
- Upgrades in line with towers
- Date formatted correctly
- Embedded Link
- Current or not
- Capitalization
This should be done for other challenges as well if applicable.

2TC formatting Improvements

---

alias-repository.js
aliases/heroes.json
aliases/maps/beginner-maps.json
aliases/towers/magic/alchemist.json
aliases/towers/magic/druid.json
aliases/towers/magic/super_monkey.json
aliases/towers/magic/wizard.json
aliases/towers/military/monkey_ace.json
aliases/towers/military/mortar_monkey.json
aliases/towers/support/engineer.json
aliases/towers/support/monkey_village.json
commands/cash.js
commands/chincome.js
commands/index-2mp.js
commands/index-2tc.js
commands/map.js
commands/round.js
helpers/general.js
parser/any-order-parser.js
parser/command-parser.js
parser/natural-number-parser.js
parser/optional-parser.js
parser/or-parser.js
parser/parsed.js

**Mainly**:
- Wrote `q!2tc` with `CommandParser`
- Allowing it to take in:
- `n, {map}` - Get combo #`n` optionally on `map`
- `map` - Get all combos on `map`
- `tower/hero, {tower/hero}, {map}` - Get all combos involving `tower/hero{s}` optionally on `map`
All of the above is stubbed out (message is sent to user saying "feature coming soon") except for the current working features which are:
- `q!2tc 44`
- `q!2tc obyn wlp`
Basically the working features are those that locate a single OG-map combo, whether via combo # or the 2 towers involved.
Alt maps and multi-combo searches are coming soon!
**Additionally**:
- Fixed a bug wherein parsing for more than one of the same type (like 2 rounds) doesn't keep both types
- Added new tower aliases to cover for 2TC towers without 2MP completions
- …

`q!2tc` searching by the 2 towers involved / bug fixes and improvements

---

commands/chincome.js
commands/income.js

Take a look thru `q!income`. There were a number of important cases that were failing so I fixed them and improved other places.

q!chincome and q!income fixes and improvements

---

alias-repository.js
commands/index-2tc.js

**Added**:
- `q!2tc <tower_upgrade/hero> <tower_upgrade_hero> <map>`
- `q!2tc <n> <map>`
**Still to go**:
- `q!2tc <map>` -- all 2tc on that map unless there are too many
- `q!2tc <tower_upgrade/hero>` all OG 2TCs containing the specified tower
- `q!2tc <tower_upgrade/hero> <map>` all 2TC containing hte specified tower on the specified map

Alt combos! Searching one combo at a time done.

---

commands/cash.js
commands/herolevel.js
commands/level.js
parser/cash-parser.js
parser/number-parser.js

Number parser now just essentially ignores commas so 2,323,234 is valid.
Removed commented out print statements.

Cash parser rather than just natural number parser

---

commands/index-2tc.js
commands/index-3tcabr.js
helpers/general.js
parser/anything-parser.js
parser/person-parser.js

Can search by 1, 2, or 3 towers.
If 0 combos are found, error is displayed.
If 1 combo is found, it displays in full information
If 2-20 combos are found, it displays a list of 3-Tower completions involving said towers. Queried towers get highlighted.
If >20 combos are found, it does the above but with reaction-emoji driven pagination!

3-Tower ABR CHIMPS searching by towers

---

alias-repository.js
commands/index-2mp.js

- Impossible maps added for water towers on non-water maps
- Headers for map difficulty commands fixed to not say `map, map, map` anymore.
- More useful helper functions in `AliasRepository`

`q!2mp` water tower improvements

---

aliases/misc.json
commands/index-2tc.js
commands/index-3tcabr.js
commands/index-lcc.js
commands/index-ltc.js
commands/index-race.js

Following @Topper64's paradigm/recommendation.

Tidy exports for index commands

---

parser/README.md

Up to date and hopefully better. Feel free to add to any sections.
Best to just look [here](https://github.com/rmlgaming/cyberquincy/blob/parser-documentation/parser/README.md) instead of the diff.

Parser documentation

---

alias-repository.js
commands/index-2mp.js

- `q!2mp <map>` with scrolling when num_combos > 15
- Removed maps from no-water-map list that have some water

`q!2mp <map>`

---

aliases/misc.json
commands/index-2mp.js
parser/person-parser.js

- `q!2mp u#rmlgaming`
- `q!2mp user#rb`

`q!2mp <user>`

---

commands/index-ltc.js

`q!ltc logs chp`
`q!ltc og dc`

LTC alt completions

---

commands/index-2mp.js

Note, we need to make sure that the bot has the right perms to remove reactions or else this doesn't work..maybe I could try to catch the permissions failed exception and go back to the old way of creating new messages?
Hold off merging, I'm going to try to create a failsafe if it doesn't have permissions.

2mp multipage results get edited in place

---

commands/find4tc.js
commands/leaderboard4tc.js
commands/submit4tc.js
jsons/leaderboard.json
jsons/remaining_combos.json
jsons/submitted_combos.json

added the basic functionality to get 4tc working with cyber quincy

introducing 4tc to cyber quincy

---

commands/index-balances.js

Finally lol. Luckily I wrote q!balance tower such that it was really easy to implement it for hero.

q!balance hero!!!

---

commands/index-balances.js

I swear I made this exact fix before, how did it get reverted?! 🤔

Fix version parsing

---

commands/calc-test.js
commands/calculator.js
commands/towers.js
helpers/calculator/lexical_parser.js
helpers/towers.js
package-lock.json
package.json

CHIMPS Cost Calculator

---

commands/towers.js
jsons/costs.json

Just tried typing `q!vil` expecting to see the `q!tower` results for a 000 village, but instead ran into like 4 different issues along the way😬

q!tower fixes

---

alias-repository.js
commands/map.js
jsons/map.json

**This PR needs `balance` filled out in the maps json, otherwise `q!map int` breaks**

`q!map` RBS Command

---

aliases/maps/beginner-maps.json
aliases/towers/military/dartling_gunner.json

Order longest to shortest as well

Fix Resort index abbr

---

commands/index-balances.js
package-lock.json
package.json

Sorry about `package.lock`...maybe you can decrease the amount added, not sure why it happens every time

Version Added balance changes

---

commands/index-fttc.js

I want `q!fttc wizard 1` to show `wiz logs` and `wiz resort`. This PR achieves this.

FTTC Improvement

---

commands/herolevelby.js

Allows users to see more starting rounds.

`q!herolevelby` enhancements with reactions

---

commands/index-balances.js

For towers, it's a different table. For heroes it was the same so we got it for free.

Parse Tower Fixes/Changes

---

aliases/maps/expert-maps.json

To allow index commands to work on blons

Blons abbreviation

---

commands/calculator.js

I don't have a local setup and would like to test this in the discord's test qbot. Ping me in discord if/when you deploy this for testing!

 Add a^b to q!calc

---

helpers/index.js
slash_commands/index-2mp.js
slash_commands/index-2tc.js

* Underscores and Spaces are treated the same in people's tags
* 2TC alt map display on the right can now be deleted

2tc alt maps to map notes

---

alias-repository.js
helpers/index.js
slash_commands/index-2mp.js
slash_commands/index-2tc.js

* Alt maps under OG may now show how close the combo is to completing all maps within a map difficulty
* Factored out the same 2mp and 2tc code into the index helper

2tc map difficulty completions improvement

---

helpers/general.js
helpers/index.js
services/index/2mp_scraper.js
slash_commands/index-2mp.js
slash_commands/index-2tc.js
slash_commands/index-fttc.js

* Factor out `displayOneOrMultiplePages` from `/2tc`, `/2mp`, and `/fttc` into Index Helper
More technical debt is being resolved here, very satisfying. This will help to create new/rewrite existing index-related commands.

Add mobile formatting back to all the main index commands!

---

helpers/towers.js
slash_commands/index-2mp.js

`isTowerUpgrade` is pretty slow

Speed up 2mp general tower search

---

alias-repository.js
slash_commands/index-2mp.js

Let user know when index needs to fix entry for 2mp alt map abbr

---

aliases/heroes.json
slash_commands/hero.js
slash_commands/tower.js

Add title to /hero

---

helpers/enemies.js

Hopefully this helps onlookers understand these recursive methods at a glance

Key Comments; Small note adjustment

---

helpers/towers.js
slash_commands/index-2mp.js

Somehow this was reverted: https://github.com/hemisemidemipresent/cyberquincy/commit/c932bfba37e925c25afb6bc1774979b8ba49b36b

/2mp Speed up general tower search

---

helpers/enemies.js

I _think_ these are the last places...

`/bloon` rounding attempt #2

---

commands/index-unsubmit.js

helper add iunsub perm

---

alias-repository.js
aliases/heroes.json
aliases/towers/magic/alchemist.json
aliases/towers/military/dartling_gunner.json
aliases/towers/military/monkey_ace.json
aliases/towers/primary/bomb_shooter.json

I had to remove some aliases that clashed

b_ == base_

---

helpers/discord.js
slash_commands/crosspath-compare.js
slash_commands/hero.js
slash_commands/index-2mp.js
slash_commands/tower.js

* `/tower` will provide a tower upgrade summary if the now-optional path is not provided
* `/crosspath-compare` will display very long non-crosspath descriptions now

`/tower` summary

---

slash_commands/tag.js
tags/tags.toml
tags/templates.js

• Added helper function to convert template tags. Eg. `{credits}` in tags.toml becomes `footer` constant from misc.json

feat(tags): toml template tag resolver

---

slash_commands/tag.js

• Fixes regression caused by hemi in e30f7dcc44b4af7c95bd09aa53536ca0b15e8c07
• Also removes redundant syntax

fix(tag): template resolver

---

register.js
server.js
slash_command_center.js

* Added helper to add an optional `hide` option to all commands.
* Extended `ChatInputCommandInteraction` to defer and reply based on option.

feat(cmd): global ephemeral option

---

register.js
slash_command_center.js

* I learned that you can have one choice in a int/string option, so here we are

feat: use choices for hide opt

---

register.js
slash_command_center.js

Reverts hemisemidemipresent/cyberquincy#202

Revert "feat: use choices for hide opt"

---

slash_commands/leaderboard.js

* Replaces funny msg with deferred reply

fix: Use intended method for this stuff

---

alias-repository.js
aliases/maps/advanced-maps.json
aliases/maps/intermediate-maps.json
slash_commands/index-2mp.js
slash_commands/index-2tc.js

Also exclude MN from heli advanced maps
Also make index entry error less disruptive to searching (the show must go on)

Add new maps v33

---

alias-repository.js
helpers/index.js
helpers/maps.js
parser/map-difficulty-parser.js
parser/map-parser.js
services/index/2mp_scraper.js
services/index/2tc_scraper.js
slash_commands/herolevel.js
slash_commands/herolevelby.js
slash_commands/index-2mp.js
slash_commands/index-2tc.js
slash_commands/map.js

I tested all the commands I touched, so hopefully nothing broke..

Maps Alias Methods to Dedicated Helper

---

slash_commands/isubmit.js

i saw it in index and it was ugly, now looks like it did before

Minor Format change

---

helpers/general.js
helpers/index.js
helpers/maps.js
services/index/2mp_scraper.js
slash_commands/index-2mp.js
slash_commands/stats-2mp.js

Introduces a basic `/2mp` overview command for viewing general completions statistics. I've only added 2 stats so far.

`/stats-2mp`

---

helpers/enemies.js

Specify bloon modifiers in `/bloon` round appearances

---

slash_commands/calculator.js

`/calc wlp` wasn't working. I fixed that and cleanup up a tiny bit
The same problem doesn't exist in `paragon-degree`; it's fine

Fix and Clean Up `/calc` Pricings

---

alias-repository.js
aliases/geraldos_shop.json
helpers/calculator/lexical_parser.js
helpers/heroes.js
helpers/maps.js
helpers/towers.js
jsons/geraldos_shop.json
parser/hero-parser.js
server.js
slash_commands/calculator.js
slash_commands/crosspath-compare.js
slash_commands/herolevel.js
slash_commands/herolevelby.js
slash_commands/index-2mp.js
slash_commands/index-balances.js
slash_commands/paragon.js
slash_commands/tower.js

* Moved hero alias methods to heroes helper
* Made heroes helper global
* Removed miscellaneous unused code references
* Cleaned up `toIndexNormalForm`
* Surfaced mismatched parentheses error from `/calc` and `/paragon-degree`
* Consolidated `isTowerUpgradeSet` and `isTowerUpgrade` into `isTowerUpgrade` with an extra param, thus making `isTowerUpgrade` fast.

`/calc` Geraldo's Shop

---

jsons/paragon.json

Ace Paragon Change

---

slash_commands/tierlist.js

config.json needs to be updated to reflect that we are on v36 rn, currently it still thinks we are on v34

added 33, 34, 35 tierlists

---

helpers/towers.js
slash_commands/adora-sac.js
slash_commands/adorasac.js

The `/adora-sac` command attempts to calculate an optimal-cost smallest-size set of towers to sac to ewwwwww adora.

ewwwwwwwww adora sac calculator

---

helpers/bloons-general.js
slash_commands/nft.js

Command syntax: `/nft unlock_round start_round end_round difficulty [better_sell_deals]`

Quincy NFT command

---

slash_commands/adora-sac.js

`/adora-sac` max_towers parameter

---

slash_commands/nft.js

because you can't place nft on deflation

remove deflation from nft.js

---

jsons/paragon.json

Version 41
Wizard Paragon's spike dmg and drain dmg got dmg changed.
Sub Paragon's ability dmg changed.

Update paragon.json v41

---

jsons/paragon.json
slash_commands/paragon.js

fix sub paragon things

---

helpers/enemies.js

fix r251 bloon speed

---

jsons/boss.json

these 3 bosses literally use the same things

fix boss custom rounds
